### PR TITLE
Bump Python 3.10 RC version for CI

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by hugovk** [comment]
RC2 just came out yesterday, will retry tomorrow to see if GHA has picked it up.

https://discuss.python.org/t/python-3-10-0rc2-is-now-available/10496

**Comment by hugovk** [comment]
> RC2 just came out yesterday, will retry tomorrow to see if GHA has picked it up.
> 
> [discuss.python.org/t/python-3-10-0rc2-is-now-available/10496](https://discuss.python.org/t/python-3-10-0rc2-is-now-available/10496)

Ready!

**Review by thombashi — APPROVED** [review]

**Comment by thombashi** [comment]
Thank you for your pull request.

**Comment by hugovk** [comment]
You're welcome, and thank you for pytablewriter.

**Pull request merged**
